---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

namespace: nextcloud

helmCharts:
- name: nextcloud
  repo: https://nextcloud.github.io/helm
  version: 3.5.1
  releaseName: nextcloud
  namespace: nextcloud
  valuesFile: values.yaml
