{{- range $es := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $es.name }}
spec:
  refreshInterval: {{ $es.refreshInterval }}
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ $es.targetName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ $es.dataKey }}
{{- end }}
