---
- name: Letsencrpt setup
  hosts: live-srv
  gather_facts: False
  become: True
  vars:
    domains:
      - app1.super001.com
  tasks:
  - name: Ensure that the required packages are installed
    dnf:
      name:
        - nginx
        - certbot
        - python3-certbot-nginx
      state: latest

  - name: Install epel-release
    dnf:
      name:
        - epel-release
      state: latest

  - name: Ensure that the required packages are installed
    dnf:
      name:
        - snapd
      state: latest

  - name: Symlink Snapd
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      state: link

  - name: Ensure that the conflicting packages are erased
    dnf:
      name:
        - certbot
      state: absent

  - name: Start Snap
    systemd:
      name: snapd.socket
      state: started
      enabled: yes

  - name: Install required packages
    snap:
      name: certbot
      classic: true

  - name: Symlink certbot
    file:
      src: /snap/bin/certbot
      dest: /usr/bin/certbot
      state: link

  - name: Stop nginx
    systemd:
      name: nginx
      state: stopped

  - name: Obtain the certificate
    shell:
      /usr/bin/certbot --nginx --non-interactive --agree-tos --email kipko11e@gmail.com -d {{ item }}
    with_items:
      - "{{ domains }}"

  - name: Ensure Nginx is killed
    shell:
      killall nginx

  - name: Start nginx
    systemd:
      name: nginx
      state: started

  - name: Add autorenew cron
    cron:
      name: Letsencrypt autorenew
      minute: "07"
      hour: "05"
      job: /usr/bin/certbot renew --quiet
