apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  labels:
    name: grafana
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus.prometheus.svc.cluster.local:9090
      isDefault: false
    - name: Loki
      type: loki
      url: http://loki.loki.svc.cluster.local:3100
      isDefault: false
