---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - configmap.yaml
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: grafana
